Add publisher indexing/faceting
UNC-Libraries/box-c pull request #1365
Opened 2022-03-16 18:13 UTC by lfarrell

https://jira.lib.unc.edu/browse/BXC-3346
Depends on https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/182

2022-03-16 18:29 UTC, bbpennel requested changes
I think we'll want to add publisher as a field that gets serialized in `SerializationUtil`.

Might be worth checking with anna if she thinks it should get returned by the API in the "full" field set https://github.com/UNC-Libraries/box-c/blob/main/web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/SearchRestController.java#L67

2022-03-16 18:29 UTC, bbpennel commented on indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
> +                        publishers.add(publisher.getValue());
```suggestion
                        publishers.add(publisher.getTextTrim());
```

2022-03-17 20:26 UTC, bbpennel approved these changes
Looks good! I think the vue code will be impacted by the creator/contributor PR. Which would you like to merge first?

2022-03-18 12:07 UTC, lfarrell commented
Merging this one first is fine.

2022-03-22 14:00 UTC, merged