Move file record pages to VueJs
UNC-Libraries/box-c pull request #1549
Opened 2023-04-03 19:25 UTC by lfarrell

https://jira.lib.unc.edu/browse/BXC-3912

2023-04-04 15:03 UTC, bbpennel requested changes
Looks good, left a few suggestions and questions

2023-04-04 15:03 UTC, bbpennel commented on web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord.jsp
>  <div class="content-wrap full_record ${isDeleted}${' '}${isProtected}">
Seems like this is empty now, should we remove it?

2023-04-04 15:37 UTC, lfarrell commented on static/js/vue-cdr-access/tests/unit/player.spec.js
> +    briefObject: {
Yeah, that's probably a good idea.

2023-04-05 20:41 UTC, bbpennel approved these changes

2023-04-05 20:41 UTC, merged