Add image download options
UNC-Libraries/box-c pull request #1578
Opened 2023-06-13 20:15 UTC by lfarrell

https://jira.lib.unc.edu/browse/BXC-4012

2023-06-15 19:21 UTC, bbpennel requested changes
This looks good! Left a few suggestions

2023-06-15 19:21 UTC, bbpennel commented on static/js/vue-cdr-access/src/components/full_record/fileDownload.vue
> +                <a v-if="validSizeOption(800)" :href="imgDownloadLink('800')" class="dropdown-item">Small JPG (800px)</a>
Would it be overkill to put these in the translation file?

2023-06-15 19:21 UTC, bbpennel commented on static/js/vue-cdr-access/src/components/full_record/fileDownload.vue
> +                <a :href="imgDownloadLink('full')" class="dropdown-item">Full Size JPG</a>
This should be moved down into the `viewOriginal` permission check, since we are requiring that permission on the server side.

2023-06-15 19:21 UTC, bbpennel commented on static/js/vue-cdr-access/src/components/full_record/fileDownload.vue
> +                <hr class="dropdown-divider">
This divider should only appear when the the Original File option is present

2023-06-15 19:47 UTC, lfarrell commented on static/js/vue-cdr-access/src/components/full_record/fileDownload.vue
> +            return (this.resourceType === 'Work' || this.resourceType === 'File') &&
The regular drop down is for non-image files. Are we offering various sizes for PDF, etc?

2023-06-15 20:27 UTC, bbpennel commented on static/js/vue-cdr-access/src/components/full_record/fileDownload.vue
> +            return (this.resourceType === 'Work' || this.resourceType === 'File') &&
hmm, the Download button on the work page is probably going away entirely sometime soon, lets not worry about changing this at the moment, unless you've already done so.

2023-06-16 13:34 UTC, bbpennel approved these changes

2023-06-16 13:35 UTC, merged