Bxc 4313 single use links api
UNC-Libraries/box-c pull request #1654
Opened 2024-01-12 16:52 UTC by sharonluong

This PR adds API endpoints for the single use links feature: https://unclibrary.atlassian.net/browse/BXC-4360

2024-01-16 17:04 UTC, bbpennel requested changes
Looks good over all, and should be close to usable in the UI

2024-01-16 17:04 UTC, bbpennel commented on web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/SingleUseKeyControllerIT.java
> +        generateDefaultCsv(csvPath, accessKey, expirationTimestamp);
To demonstrate that generate and access work together, it would be nice to use the POST endpoint to create a single use line, and then access it

2024-01-16 17:04 UTC, bbpennel commented on web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/SingleUseKeyControllerIT.java
> +        assertEquals(content.length(), response.getContentLength());
Since we're doing "equals" at line 172, I don't think we need to compare the response length here.

2024-01-16 17:54 UTC, sharonluong commented on web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/SingleUseKeyController.java
> +            log.error("error is", e);
Ah yeah, I think I had this in when trying to debug and didn't remember to make it more detailed. I think I'll try removing it.

2024-01-17 13:53 UTC, bbpennel approved these changes

2024-01-17 13:53 UTC, bbpennel commented on web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/SingleUseKeyController.java
> +            throw new RepositoryException("Single use key is not valid: " + accessKey);
The message probably isn't accurate anymore, can make it a generic "Failed to download file using single use key" or something like that.

2024-01-17 20:36 UTC, bbpennel requested changes

2024-01-17 20:36 UTC, bbpennel commented on static/js/vue-cdr-access/tests/unit/singleUseLink.spec.js
> +const response_date = { link: `https://test.edu`, key: `12345`, expires: '24hrs', id: uuid };
It seems like "link" no longer exists, so we should remove it here to avoid confusion

2024-01-19 13:39 UTC, bbpennel approved these changes

2024-01-19 13:39 UTC, merged