Add streaming type for streaming content
UNC-Libraries/box-c pull request #1759
Opened 2024-06-26 15:26 UTC by lfarrell

- https://unclibrary.atlassian.net/browse/BXC-4622
- https://unclibrary.atlassian.net/browse/BXC-4623

Relies on https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/272

2024-06-27 17:49 UTC, sharonluong requested changes
I think we should add a test to ValidateContentModelJobTest if there is a Streaming URL but no streaming type.

2024-06-27 17:50 UTC, sharonluong commented
Are there accepted values for StreamingType?

2024-06-27 17:56 UTC, sharonluong requested changes
looking pretty good!

2024-06-27 17:56 UTC, sharonluong commented on deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJob.java
> +        var streamingType = resource.hasProperty(Cdr.streamingType);
Are there accepted values for StreamingType?

2024-06-27 17:56 UTC, sharonluong commented on indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetStreamingPropertiesFilterTest.java
> +        filter = new SetStreamingPropertiesFilter();
should add assertions for streaming type as well

2024-06-27 18:12 UTC, bbpennel requested changes

2024-06-28 16:02 UTC, bbpennel requested changes

2024-06-28 16:02 UTC, bbpennel commented on services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
> +                return "Streaming type is not a valid stream reaper type";
"Streaming type is not a valid type" so we aren't as tightly coupled with stream reaper.

2024-06-28 16:50 UTC, sharonluong approved these changes

2024-06-28 17:34 UTC, merged