Clover viewer
UNC-Libraries/box-c pull request #1815
Opened 2024-10-11 20:30 UTC by lfarrell

https://unclibrary.atlassian.net/browse/BXC-4750

2024-10-14 15:09 UTC, bbpennel requested changes

2024-10-14 15:09 UTC, bbpennel commented on web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestService.java
> +    private static final List<String> FILE_TYPES = Arrays.asList(VIDEO_MP4.toString(), VIDEO_MPEG.toString(),
hmm wonder if there are going to be conflicts with Kara's m4a ticket, probably a good reason to get this merged in

2024-10-14 18:10 UTC, lfarrell commented on web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/DatastreamUtil.java
> +        for (String format : formatTypes) {
Doesn't this one do that https://github.com/UNC-Libraries/box-c/blob/2260bde321bdfed7df620eb820b8601646d158f3/web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/DatastreamUtilTest.java#L116. I've added a check for the text file as well.

2024-10-14 20:12 UTC, bbpennel commented on web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/DatastreamUtil.java
> +        for (String format : formatTypes) {
Oh yeah, I looked at that test but missed that there were two mimetypes on the same line. Maybe we could update the name of the method to indicate that it is testing for multiple mimetypes?

2024-10-15 13:19 UTC, bbpennel commented on search-solr/src/main/java/edu/unc/lib/boxc/search/solr/filters/HasValuesFilter.java
> +        return filter.toString();
Could probably be simplified with a stream:
```
fieldValue.stream().map(v -> getFieldKey().getSolrField() + ":" + v)
                               .collect(Collectors.joining(" OR "));
```

2024-10-15 13:19 UTC, bbpennel commented on search-solr/src/main/java/edu/unc/lib/boxc/search/solr/filters/HasValuesFilter.java
> +    private final List<String> fieldValue;
Should rename to "fieldValues"

2024-10-16 13:23 UTC, bbpennel approved these changes

2024-10-16 13:23 UTC, merged